scheduled_job_5mins:
  script:
    - echo "This is scheduled job running every 5 minutes"
  rules:
    - if: '$CI_PIPELINE_SOURCE == "schedule" && $CI_PIPELINE_SCHEDULE_CRON == "5 * * * *"' 

scheduled_job_10mins:
  script:
    - echo "This is scheduled job running every 10 minutes"
  rules:
    - if: '$CI_PIPELINE_SOURCE == "schedule" && $CI_PIPELINE_SCHEDULE_CRON == "10 * * * *"'
job:
  rules:
    - if: $CI_PIPELINE_SOURCE == "push"
  script:
    - echo "push job"