job:on-schedule:
  rules:
    - if: $CI_PIPELINE_SOURCE == "schedule"
  script:
    - echo "hello world schedule"

job:
  rules:
    - if: $CI_PIPELINE_SOURCE == "push"
  script:
    - echo "push job"